input.onButtonPressed(Button.AB, function () {
    music.setVolume(music.volume())
    for (let index = 0; index < 4; index++) {
        music.playMelody("E D F A B A G F ", 120)
        music.playMelody("D C G A E G C E ", 120)
        music.playMelody("G A B A G F E D ", 120)
        music.playMelody("F G A G F E D C ", 120)
        music.playMelody("D C G A E G C E ", 120)
        music.playMelody("G A B A G F E D ", 120)
        music.playMelody("F G A G F E D C ", 120)
        music.playMelody("D C G A E G C E ", 120)
        music.playMelody("E D F A B A G F ", 120)
        music.playMelody("C D E E D E G F ", 120)
        for (let index = 0; index < 4; index++) {
            for (let index = 0; index < 4; index++) {
                music.playMelody("E D F A B A G F ", 120)
                music.playMelody("D C G A E G C E ", 120)
                music.playMelody("G A B A G F E D ", 120)
                music.playMelody("F G A G F E D C ", 120)
                music.playMelody("D C G A E G C E ", 120)
                music.playMelody("G A B A G F E D ", 120)
                music.playMelody("F G A G F E D C ", 120)
                music.playMelody("D C G A E G C E ", 120)
                music.playMelody("E D F A B A G F ", 120)
                music.playMelody("C D E E D E G F ", 120)
                for (let index = 0; index < 4; index++) {
                    music.playMelody("E D F A B A G F ", 120)
                    music.playMelody("D C G A E G C E ", 120)
                    music.playMelody("G A B A G F E D ", 120)
                    music.playMelody("F G A G F E D C ", 120)
                    music.playMelody("D C G A E G C E ", 120)
                    music.playMelody("G A B A G F E D ", 120)
                    music.playMelody("F G A G F E D C ", 120)
                    music.playMelody("D C G A E G C E ", 120)
                    music.playMelody("E D F A B A G F ", 120)
                    music.playMelody("C D E E D E G F ", 120)
                }
            }
            music.playMelody("E D F A B A G F ", 120)
            music.playMelody("D C G A E G C E ", 120)
            music.playMelody("G A B A G F E D ", 120)
            music.playMelody("F G A G F E D C ", 120)
            music.playMelody("D C G A E G C E ", 120)
            music.playMelody("G A B A G F E D ", 120)
            music.playMelody("F G A G F E D C ", 120)
            music.playMelody("D C G A E G C E ", 120)
            music.playMelody("E D F A B A G F ", 120)
            music.playMelody("C D E E D E G F ", 120)
        }
    }
})
for (let index = 0; index < randint(1, input.lightLevel()); index++) {
    input.setSoundThreshold(SoundThreshold.Loud, 128)
}
led.plot(1, 1)
basic.pause(200)
led.plot(0, 1)
basic.pause(200)
led.plot(0, 0)
basic.pause(200)
led.plot(1, 0)
basic.pause(200)
led.plot(3, 1)
basic.pause(200)
led.plot(4, 1)
basic.pause(200)
led.plot(4, 0)
basic.pause(200)
led.plot(3, 0)
basic.pause(200)
led.plot(0, 3)
basic.pause(200)
led.plot(1, 4)
basic.pause(200)
led.plot(2, 4)
basic.pause(200)
led.plot(3, 4)
basic.pause(200)
led.plot(4, 3)
basic.pause(200)
led.plot(5, 4)
basic.pause(200)
led.plot(6, 4)
